### ISSUE TITLE
Vindicators named Johny killed bolloom entities

### ISSUE THREAD

**Issue by five0five** [SnappyDragon18/Endergetic#7]
I imagine this applies to any mob that kills any other mob (the wither for example) and probably levitating poise too

**Comment by SmellyModder** [comment]
Alright so. Vindicators attacking them is something I can't exactly fix right now due to the entities having to extend EntityLiving because of forge having an issue with registering just stuff that extends Entity and the vindicator kills anything that's a living entity except for the other illagers. As for the wither, I made the wither not try to kill them anymore. I will fix the Johnny bug when forge becomes more stable
